module.exports = [
  {
    userType: "individual",
    user_member_id: "11",
    user_member_pw: "11",
    user_member_name: "김일일 ",
    user_member_num: "19910101",
    user_member_jibunAddress: "경북 영천시 금호읍 덕성리 95-9",
    user_member_detailAddress: "11번지",
    user_member_roadAddress: "경북 영천시 금호읍 대구대길 7",
    user_member_tel: "01012341111",
    user_member_email: "11@11.com",
    user_resume_title: "이력서제목1",
    user_resume_schoolMajor: "경영학과1",
    user_resume_schoolPeriod1Year: "2000",
    user_resume_schoolPeriod1Month: "01",
    user_resume_schoolPeriod2Year: "2001",
    user_resume_schoolPeriod2Month: "02",
    user_resume_schoolFinal: "졸업(예정)",
    user_resume_hopeCompany: "회계법인",
    user_resume_hopeRegion1: "대구",
    user_resume_hopeRegion2: "포항",
    user_resume_hopeRegion: 0,
    user_resume_hopePayType1: "월급",
    user_resume_hopePayType2: "7000000",
    user_resume_hopePay: null,
    user_resume_hopeWork1: 1,
    user_resume_hopeWork2: null,
    user_resume_hopeWork3: null,
    user_resume_hopeWork4: 0,
    user_resume_hopeStartYear: "2000",
    user_resume_hopeStartMonth: "3",
    user_resume_hopeStartDay: "5",
    user_resume_hopeWorkTime1Hour: "09",
    user_resume_hopeWorkTime1Minute: "00",
    user_resume_hopeWorkTime2Hour: "15",
    user_resume_hopeWorkTime2Minute: "00",
  },
  {
    userType: "individual",
    user_member_id: "22",
    user_member_pw: "22",
    user_member_name: "이이이",
    user_member_num: "19920202",
    user_member_jibunAddress: "서울 서대문구 충정로3가 31-35",
    user_member_detailAddress: "22번지",
    user_member_roadAddress: "서울 서대문구 경기대로1길 8",
    user_member_tel: "01012342222",
    user_member_email: "22@22.com",
    user_resume_title: "이력서제목2",
    user_resume_schoolMajor: "경영학과2",
    user_resume_schoolPeriod1Year: "2002",
    user_resume_schoolPeriod1Month: "02",
    user_resume_schoolPeriod2Year: "2002",
    user_resume_schoolPeriod2Month: "03",
    user_resume_schoolFinal: "졸업(예정)",
    user_resume_hopeCompany: "회계법인",
    user_resume_hopeRegion1: "대구",
    user_resume_hopeRegion2: "포항",
    user_resume_hopeRegion: 0,
    user_resume_hopePayType1: "월급",
    user_resume_hopePayType2: "7000000",
    user_resume_hopePay: null,
    user_resume_hopeWork1: 1,
    user_resume_hopeWork2: null,
    user_resume_hopeWork3: null,
    user_resume_hopeWork4: 0,
    user_resume_hopeStartYear: "2000",
    user_resume_hopeStartMonth: "3",
    user_resume_hopeStartDay: "5",
    user_resume_hopeWorkTime1Hour: "09",
    user_resume_hopeWorkTime1Minute: "00",
    user_resume_hopeWorkTime2Hour: "15",
    user_resume_hopeWorkTime2Minute: "00",
  },
  {
    userType: "individual",
    user_member_id: "33",
    user_member_pw: "33",
    user_member_name: "박삼삼",
    user_member_num: "19930303",
    user_member_jibunAddress: "경북 안동시 정하동 636-12",
    user_member_detailAddress: "33번지",
    user_member_roadAddress: "경북 안동시 강남11길 36",
    user_member_tel: "01012343333",
    user_member_email: "33@3.com",
    user_resume_title: "이력서제목3",
    user_resume_schoolMajor: "경영학과3",
    user_resume_schoolPeriod1Year: "2000",
    user_resume_schoolPeriod1Month: "03",
    user_resume_schoolPeriod2Year: "2003",
    user_resume_schoolPeriod2Month: "03",
    user_resume_schoolFinal: "졸업(예정)",
    user_resume_hopeCompany: "회계법인",
    user_resume_hopeRegion1: "대구",
    user_resume_hopeRegion2: "포항",
    user_resume_hopeRegion: 0,
    user_resume_hopePayType1: "월급",
    user_resume_hopePayType2: "7000000",
    user_resume_hopePay: null,
    user_resume_hopeWork1: 1,
    user_resume_hopeWork2: null,
    user_resume_hopeWork3: null,
    user_resume_hopeWork4: 0,
    user_resume_hopeStartYear: "2000",
    user_resume_hopeStartMonth: "3",
    user_resume_hopeStartDay: "5",
    user_resume_hopeWorkTime1Hour: "09",
    user_resume_hopeWorkTime1Minute: "00",
    user_resume_hopeWorkTime2Hour: "15",
    user_resume_hopeWorkTime2Minute: "00",
  },
];
