module.exports = [
  {
    no: 1,
    name: "김일일",
    school: "대구가톨릭대학교",
    major: "경영학과",
    career: "1",
    workType: "모두가능",
    region: "대구 수성구 신매동",
    start: "202402",
    point: 0,
  },
  {
    no: 2,
    name: "김이이",
    school: "대구가톨릭대학교",
    major: "경영학과",
    career: "2",
    workType: "모두가능",
    region: "대구 수성구 매호동",
    start: "202403",
    point: 0,
  },
  {
    no: 3,
    name: "김삼삼",
    school: "대구가톨릭대학교",
    major: "경영학과",
    career: "3",
    workType: "재택",
    region: "대구 수성구 신매동",
    start: "202404",
    point: 0,
  },
  {
    no: 4,
    name: "김사사",
    school: "대구가톨릭대학교",
    major: "경영학과",
    career: "4",
    workType: "재택",
    region: "대구 북구 복현동",
    start: "202405",
    point: 0,
  },
  {
    no: 5,
    name: "김오오",
    school: "대구대학교",
    major: "경영학과",
    career: "5",
    workType: "재택",
    region: "대구 북구 복현동",
    start: "202407",
    point: 0,
  },
  {
    no: 6,
    name: "김육육",
    school: "대구대학교",
    major: "경영학과",
    career: "6",
    workType: "재택",
    region: "대구 북구 대현동",
    start: "202411",
    point: 0,
  },
  {
    no: 7,
    name: "김칠칠",
    school: "대구대학교",
    major: "경영학과",
    career: "17",
    workType: "출근",
    region: "대구 동구 감삼동",
    start: "202503",
    point: 0,
  },
  {
    no: 8,
    name: "김팔팔",
    school: "대구대학교",
    major: "경영학과",
    career: "21",
    workType: "출근",
    region: "서울 동구 감삼동",
    start: "202501",
    point: 0,
  },
  {
    no: 9,
    name: "김구구",
    school: "대구대학교",
    major: "경영학과",
    career: "3",
    workType: "모두가능",
    region: "부산 서구 대구동",
    start: "202410",
    point: 0,
  },
  {
    no: 10,
    name: "김십십",
    school: "대구대학교",
    major: "경영학과",
    career: "0",
    workType: "모두가능",
    region: "부산 서구 대구동",
    start: "202401",
    point: 0,
  },
];
